---
- name: ping_check
  hosts: all
  gather_facts: no
  tasks:
    - name: verificare_ping
      shell: ping -c 1 {{ansible_host}}
      register: ping_result
      ignore_errors: yes

    - name: raspunde
      ansible.builtin.debug:
        msg: "Host-ul {{ inventory_hostname }} cu IP:{{ ansible_host }} raspunde la ping"
      when: "'UNREACHABLE' not in ping_result.stdout"

    - name: nu_raspunde
      ansible.builtin.debug:
        msg: "Host-ul {{ inventory_hostname }} cu IP {{ ansible_host }} NU raspunde la ping"
      when: "'UNREACHABLE' in ping_result.stdout"
