---
- name: ping_check
  hosts: all
  gather_facts: no
  tasks:
    - name: verificare_ping
      ansible.builtin.ping:
      register: ping_result

    - name: raspunde
      debug:
        msg: "Host-ul {{ inventory_hostname }} ({{ ansible_host }}) raspunde la ping"
      when: ping_result.ping

    - name: nu_raspunde
      debug:
        msg: "Host-ul {{ inventory_hostname }} ({{ ansible_host }}) NU raspunde la ping"
      when: not ping_result.ping
